### PR TITLE
Add Comments.tmPreferences

### PR DESCRIPTION
**Pull request by jfromaniello**
With this change the user can do toggle comments on sublime.

### CODE REVIEW

**Comment by matt-moser** [comment]
With respect to your changes, I just tested your preferences, and don't see any impact to highlighting around comments.  If you provide an update to the test.avdl file to demonstrate the improved comment highlighting, I could accept this PR.  

That being said... This project is no longer being maintained.  I'll update the README to reflect that.  If you'd like me to reference your fork for future users, I can do that.  Otherwise, this project will just be deprecated.

**Comment by jfromaniello** [comment]
It doesn't affect highlighting, just enables toggling a line into comments.

**Comment by matt-moser** [comment]
Ah.. I've tested, and this looks good.  Accepting.

**Comment by jfromaniello** [comment]
Thanks a lot

**Pull request merged**
